### ISSUE TITLE
Make singular/plural definitions extendable

### ISSUE THREAD

**Issue by mgwidmann** [girishramnani/inflector#1]
This is important as you'll never be able to cover all possible cases, especially when it comes to jargon and other words that reside around any particular domain.

Here are a few different ways you could do this, I'll let you decide.

1. Simple additions to the regex: Add a `++ Application.get_env(:inflextorex, :singlular_uninflected, [])` to each regex. The user could build a `config/inflections.exs` which could be imported inside `config/config.exs`
2. Make a DSL. Allow the user to do a `use` on a DSL module you create and then make a macro to add additional definitions. The user would then likely use this new module you've helped them build in order to interface with your package. It may be best to only store in this module the additions and build it to fall back to your current implementation.
3. A mix of the above two, build a wrapper around `Mix.Config` which exposes a DSL to add new inflections. Make a mix task to create the `config/inflections.exs` with some examples and comments and append an import to `config/config.exs`. Your macro for adding new inflections expands to simple mix config settings.

**Comment by girishramnani** [comment]
Thanks for the suggestions.

**Comment by girishramnani** [comment]
going with the first approach.
